test:
  _target_: src.datasets.LenslessDataset
  dataset_path: "data/DigiCam-Mirflickr-MultiMask-10K/dataset"
  masks_path: "data/DigiCam-Mirflickr-MultiMask-10K/masks"
  split: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
  limit: 100
